feat(bar): Add proper datetime module

diff --git a/scripts/lockDependencies b/scripts/lockDependencies
--- a/scripts/lockDependencies
+++ b/scripts/lockDependencies
@@ -1,13 +1,16 @@
 #!/usr/bin/env bash
 # Run 'pub get' in all packages and convert pubspec.lock to JSON for use in Nix
 
+# Fail on error
+set -e
+
 FLAKE_ROOT="$(nix flake metadata --json | jq -r '.original.url' | cut -c 8-)"
 
 function generate_pubspec_lock_json() {
   yq . $1/pubspec.lock > $1/pubspec.lock.json;
 }
 
-packages=$(nix flake show --json --quiet --quiet | jq '.packages' | jq -r 'map(keys) | add | join("\n")')
+packages=$(nix flake show --json --quiet --quiet | jq '.packages' | jq -r 'map(keys) | add | map(select(. != "default")) | join("\n")')
 echo "$packages" | while read -r package; do
   echo "Running 'pub get' in $package";
   flutter pub get --directory="$FLAKE_ROOT/packages/memex_$package";
